### ISSUE TITLE
Node.js support

### ISSUE THREAD

**Issue by shahidcodes** [abelalvarez89/xlsx-parse-json#8]
I could not find any documentation usage in node.js. If this lib already supports it then it would be good to have it in documentation.

**Comment by abelalvarez89** [comment]
The library is meat to be used with node, angular, react or any JS framwork. It takes the actual file as input, not a file path. If you add more description I can help you use the library.

**Comment by miguelguadarrama** [comment]
@abelalvarez89 Do you mean node or javascript? Because you compare node with angular or react or any JS framework, which is odd, since they are not the same thing. Your library requires FileReader, and this is available on the client (browser, web API) but not on node. So this is not a node library.

**Comment by abelalvarez89** [comment]
Currently only supporting web applications
